OnlineShop/OnlineShopWebApp/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDb.Interfaces;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("admin")]
    public class RoleController : Controller
    {
        readonly IRolesStorage _rolesStorage;

        public RoleController(IRolesStorage rolesStorage)
        {
            _rolesStorage = rolesStorage;
        }

        public IActionResult AddRolePanel()
        {
            return View();
        }
        public IActionResult AddRole(string name)
        {
            _rolesStorage.AddRole(name);
            return RedirectToAction("WatchRoles");
        }
        public IActionResult RemoveRole(string name)
        {
            _rolesStorage.RemoveRole(name);
            return RedirectToAction("WatchRoles");
        }

        public IActionResult WatchRoles()
        {
            return View(Mapping.Maps.ToRoleListViewModel(_rolesStorage.LoadRolesList()));
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDb.Interfaces;
using System.Linq;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("admin")]
    public class UserController : Controller
    {
        readonly IUserStorage _userStorage;

        public UserController(IUserStorage userStorage)
        {
            _userStorage = userStorage;
        }
        public IActionResult WatchUsers()
        {
            return View(Mapping.Maps.ToUserListViewModel(_userStorage.LoadUsersList()));
        }

        public IActionResult WatchUserInfo(int id)
        {
            var users = _userStorage.LoadUsersList();
            var existingUser = users.FirstOrDefault(p => p.Id == id);
            return View(Mapping.Maps.ToUserViewModel(existingUser));
        }

        public IActionResult EditPassword(int id, string password)
        {
            var user = _userStorage.LoadUsersList().FirstOrDefault(p => p.Id == id);
            _userStorage.EditPassword(id, password);
            return View(Mapping.Maps.ToUserViewModel(user));
        }

        public IActionResult EditData(int id, string name)
        {
            var user = _userStorage.LoadUsersList().FirstOrDefault(p => p.Id == id);
            _userStorage.EditData(id, name);
            return View(Mapping.Maps.ToUserViewModel(user));
        }

        public IActionResult DeleteUser(int id)
        {
            _userStorage.DeleteUser(id);
            return RedirectToAction("WatchUsers");
        }

        public IActionResult AddUser(string name, string password)
        {
            _userStorage.UserRegistration(name, password);
            return RedirectToAction("WatchUsers");
        }

        public IActionResult AddUserForm()
        {
            return View();
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDb.Interfaces;
using System.Linq;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        readonly IProductStorage _productStorage;

        public ProductController (IProductStorage productStorage)
        {
            _productStorage = productStorage;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var products = _productStorage.LoadProducts();
            var item = products.FirstOrDefault(x => x.Id == id);
            if (id == 0) return View(products);
            return View(item == null ? null : new[] { item });
        }
       
        public IActionResult Search(string searchText)
        {
            if (searchText != null)
            {
                var products = _productStorage.LoadProducts();
                var itemFind = products.Where(product => product.Name.ToLower().Contains(searchText.ToLower())).ToList();
                return View(Mapping.Maps.ToProductListViewModel(itemFind));
            }
            else
                return RedirectToAction("Index", "Home");
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Admin/AdminPanel.cshtml
<h1>Админ панель</h1>

<ul>
    <li><a asp-controller="Admin" asp-action="WatchOrders" asp-area="Admin">Заказы</a></li>
    <li><a asp-controller="User" asp-action="WatchUsers" asp-area="Admin">Пользователи</a></li>
    <li><a asp-controller="Role" asp-action="WatchRoles" asp-area="Admin">Роли</a></li>
    <li><a asp-controller="Product" asp-action="WatchProducts" asp-area="Admin">Продукты</a></li>
</ul>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Admin/WatchOrders.cshtml
@model List<OrderViewModel>


<h1>Список заказов</h1>

@if (Model?.Count > 0)
{
    <table style="border-collapse: collapse; width: 100%;">
        <thead>
            <tr style="background-color: #f2f2f2;">
                <th style="border: 1px solid #ddd; padding: 8px;">Имя пользователя</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Адрес</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Список товаров</th>
                <th style="border: 1px solid #ddd; padding: 8px;">Статус заказа</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td style="border: 1px solid #ddd; padding: 8px;">@order.CustomerName</td>
                    <td style="border: 1px solid #ddd; padding: 8px;">@order.ShippingAddress</td>
                    <td style="border: 1px solid #ddd; padding: 8px;">@order.ProductCart
                        <ul>
                          
                        </ul>
                    </td>
                    <td style="border: 1px solid #ddd; padding: 8px;">
                        <select onchange="location = this.value;">
                            <option>@order.OrderStatus</option>
                            <option value="/admin/admin/updateorderstatus?orderId=@order.OrderId&status=Обработан">Обработан</option>
                            <option value="/admin/admin/updateorderstatus?orderId=@order.OrderId&status=Отправлен">Отправлен</option>
                            <option value="/admin/admin/updateorderstatus?orderId=@order.OrderId&status=Доставлен">Доставлен</option>
                            <option value="/admin/admin/updateorderstatus?orderId=@order.OrderId&status=Отменен">Отменен</option>
                        </select>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Список заказов пуст.</p>
}