OnlineShop/OnlineShopWebApp/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDb.Interfaces;

namespace OnlineShopWebApp.Controllers
{
    public class AuthorizationController : Controller
    {
        readonly IUserStorage _userStorage;
        readonly ICartStorage _cartStorage;

        public AuthorizationController(IUserStorage userStorage, ICartStorage cartStorage)
        {
            _userStorage = userStorage;
            _cartStorage = cartStorage;
        }
        public IActionResult RegistrationForm()
        {
            ViewBag.CartCount = _cartStorage.LoadCartCount();
            return View();
        }

        public IActionResult LoginForm()
        {
            ViewBag.CartCount = _cartStorage.LoadCartCount();
            return View();
        }

        [HttpPost]
        public IActionResult AcceptLogin(string name, string password)
        {
            var loginResult = _userStorage.UserLogin(name, password);

            if (!loginResult)
            {
                TempData["ErrorMessage"] = "Неверный логин или пароль";
                return RedirectToAction("Error", "Home");
            }
            return View();
        }

        public IActionResult AcceptRegistration(string name, string password)
        {
            _userStorage.UserRegistration(name, password);
            return View();
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDb.Interfaces;
using System.Linq;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        readonly IProductStorage _productStorage;

        public ProductController (IProductStorage productStorage)
        {
            _productStorage = productStorage;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var products = _productStorage.LoadProducts();
            var item = products.FirstOrDefault(x => x.Id == id);
            if (id == 0) return View(products);
            return View(item == null ? null : new[] { item });
        }
       
        public IActionResult Search(string searchText)
        {
            if (searchText != null)
            {
                var products = _productStorage.LoadProducts();
                var itemFind = products.Where(product => product.Name.ToLower().Contains(searchText.ToLower())).ToList();
                return View(Mapping.Maps.ToProductListViewModel(itemFind));
            }
            else
                return RedirectToAction("Index", "Home");
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <img src="@Url.Content("~/images/homePage/headPicture.jpg")" style="width:100%; height:auto;">

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Список товаров</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

            <div class="container d-flex justify-content-between">
                <a class="navbar-brand styled-brand" asp-area="" asp-controller="Home" asp-action="Index">Магазин игровых девайсов</a>
                <div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                        <form class="d-flex" role="search" method="post">
                            <input name="searchText" class="form-control" type="search" aria-label="Поиск">
                            <button class="btn btn-dark" type="submit" asp-controller="Product" asp-action="Search">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                </svg>
                            </button>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Вернуться домой">
                                    <i class="fa-solid fa-house fa-2x"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-action="AdminPanel" title="Админ панель">
                                    <i class="fa-solid fa-gears fa-2x"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="LoginForm" title="Войти">
                                    <i class="fa-solid fa-address-card fa-2x"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Compare" asp-action="CompareProducts" title="Сравнить товары">
                                    <i class="fas fa-code-compare fa-2x"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Favourites" asp-action="FavouritesList" title="Избранное">
                                    <i class="fa-solid fa-heart fa-2x"></i>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="WatchCart" title="Корзина">
                                    <i class="fa-solid fa-cart-shopping fa-2x"></i>
                                    <span class="badge badge-light" id="cart-counter" style="color: red;">@ViewBag.CartCount</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineGameShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial");
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>